### ISSUE TITLE
What do you mean by spark?

### ISSUE THREAD

**Issue by thedonquixotic** [diepet/plugin.video.spark#1]
I found an article talking about the Spark Kodi build but I can't find an official site for it or anything, so I checked on github to see if there was a repo and I found this repo. You say you are using spark as your OS? Is that the same thing as this? https://www.technadu.com/spark-kodi-build/12961/

**Comment by diepet** [comment]
Hi David,
my plugin is a different stuff.

My plugin needs to be installed in a system having Kodi installed. Then
from there you can see the channel list of the Spark system and to stream a
video from the Spark machine to the Kodi instance installed in the other
system.

Bye


Il 23 lug 2018 2:28 AM, "David Aslan French" <notifications@github.com> ha
scritto:

I found an article talking about the Spark Kodi build but I can't find an
official site for it or anything, so I checked on github to see if there
was a repo and I found this repo. You say you are using spark as your OS?
Is that the same thing as this?
https://www.technadu.com/spark-kodi-build/12961/

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/diepet/plugin.video.spark/issues/1>, or mute the thread

**Comment by thedonquixotic** [comment]
Cool, thanks. Good luck with your project!
